### ISSUE TITLE
Syslog Fehlermeldung nach WeeWX Update auf 4.9.x

### ISSUE THREAD

**Issue by c0by85** [roe-dl/weewx-wns#2]
Nach dem Update von WeeWX Update auf 4.9.x gibt es im Syslog eine Fehlermeldung.

```
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: Wns: Unexpected exception of type <class 'TypeError'>
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: *** Traceback (most recent call last):
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 379, in run_loop
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***     self.process_record(_record, dbmanager)
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 425, in process_record
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***     _full_record = self.get_record(record, dbmanager)
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***   File "/usr/share/weewx/user/wns.py", line 540, in get_record
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: ***     yesterdaytimespan = weeutil.weeutil.archiveDaySpan(_time_ts,1,1)
Oct 25 09:10:17 weather weewx[982] ERROR weewx.restx: *** TypeError: archiveDaySpan() takes from 1 to 2 positional arguments but 3 were given

Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: Wns: Unexpected exception of type <class 'TypeError'>
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: *** Traceback (most recent call last):
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 379, in run_loop
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***     self.process_record(_record, dbmanager)
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***   File "/usr/share/weewx/weewx/restx.py", line 425, in process_record
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***     _full_record = self.get_record(record, dbmanager)
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***   File "/usr/share/weewx/user/wns.py", line 540, in get_record
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: ***     yesterdaytimespan = weeutil.weeutil.archiveDaySpan(_time_ts,1,1)
Oct 25 14:58:17 weather weewx[15683] ERROR weewx.restx: *** TypeError: archiveDaySpan() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by roe-dl** [comment]
Zwischeninfo: In weeutil/weeutil.py wurde die Funktion archiveDaySpan geändert.

alte Version: `def archiveDaySpan(time_ts, grace=1, days_ago=0)`
neue Verison: `def archiveDaySpan(time_ts, days_ago=0)`

Korrektur folgt.

**Comment by roe-dl** [comment]
See https://github.com/weewx/weewx/commit/0f558a00c15af9ef830b7b944d66aaaf45ff9711

**Comment by roe-dl** [comment]
Tom Keffer höchstselbst hat einen Pull-Request dazu eingereicht, den ich gerade übernommen habe.

#3
